# Generated by Django 5.0.7 on 2024-07-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('location', models.IntegerField(default=0)),
                ('desc', models.IntegerField(default=0)),
                ('type', models.JSONField(default=list)),
                ('applicants', models.CharField(max_length=1000)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
