# Generated by Django 5.0.8 on 2024-08-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="resume_url",
        ),
    ]
