# Generated by Django 5.0.7 on 2024-07-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_categories_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='closed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categories',
            name='counts',
            field=models.IntegerField(default=0),
        ),
    ]
